config/routes.rb
Rails.application.routes.draw do

  resource :users
  post "send_code" => 'verify_code#send_code'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :mobile, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    verify_code = params[:user][:verify_code]
    if verify_code == session[:user][:verify_code]
      if user.save
        redirect_to root
      else
        render "new"
      end
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def  user_params
    params.require(:user).permit(:mobile, :password, :is_admin)
  end
end

app/controllers/verify_code_controller.rb
class VerifyCodeController < ApplicationController
  def send_code
    mobile = params[:mobile]
    verify_code = { code: generate_code, expire_at: Time.now + 2.minutes, auth_state: false }
    if VerifyCodeHelper.send_auth_code_sms mobile, verify_code[:code]
      session[:verify_code] = verify_code
      render js: "alert(#{session[:verify_code][:code]})"
    else
      render js: "alert('手机发送验证码失败')"
    end
  end

  def activated?
    !session[:verify_code][:auth_state] && Time.now < session[:verify_code][:expire_at]
  end
  private
    def generate_code
      ((0...9).to_a.sample(3) + (0...9).to_a.sample(3)).join()
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verify_code_helper.rb
module VerifyCodeHelper
  def self.send_auth_code_sms number, code
    # unless Rails.env == 'production'
    #   return true
    # end
    require 'net/http'
    require 'uri'
    params = {}
    #修改为您的apikey.可在官网（http://www.yuanpian.com)登录后用户中心首页看到
    apikey = 'a7c5a16db339447d3f950df468c87251'
    #修改为您要发送的手机号码，多个号码用逗号隔开
    mobile = number
    #修改为您要发送的短信内容
    text = '【97gun】您的验证码是 #{code}'
    #智能匹配模板发送HTTP地址
    send_sms_uri = URI.parse('https://sms.yunpian.com/v2/sms/single_send.json')
    params['apikey'] = apikey
    #打印用户信息
    # response =  Net::HTTP.post_form(get_user_info_uri,params)
    # print response.body + "\n"

    params['mobile'] = mobile
    params['text'] = text
    #智能匹配模板发送
    response = Net::HTTP.post_form(send_sms_uri,params)
    print response.body + "\n"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/new.html.erb
<h1>注册</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label "手机号" %>
      <%= f.text_field :mobile %>
      <input type="button" id="btn" value="免费获取验证码" />
      <%= f.label "验证码" %>
      <%= f.text_field :verify_code %>
      <%= f.label "密码" %>
      <%= f.password_field :password %>
      <%= f.label "确认密码" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "创建" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
var wait=60;
function time(o) {
  if (wait == 0) {
      o.removeAttribute("disabled");
      o.value="免费获取验证码";
      wait = 60;
  } else {
      o.setAttribute("disabled", true);
      o.value="重新发送(" + wait + ")";
      wait--;
      setTimeout(function() {
          time(o)
      },
      1000)
  }
}
$('#btn').click(function(){
  var mobile = document.getElementById("user_mobile")
  if (mobile.value==0){
    return false;
  }
  else{
    time(this);
    $.ajax({
      type: 'POST',
      url: '<%= send_code_path %>',
      data: {
        mobile: function(){
          return $("#user_mobile").val()
        }
      }
    })
  }
});
// document.getElementById("btn").onclick=function(){time(this);}
</script>